replicaCount: 2

image:
  repository: portfolio
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80

monitoring:
  enabled: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
