name: Portfolio CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t portfolio .

    - name: Run container test
      run: docker run -d -p 8080:80 portfolio